[package]
name = "sample_server"
version = "0.1.0"
authors = ["StreatCodes <matt.r.streatfield@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.39"
sodiumoxide = "0.2.2"
base64 = "0.10.1"
env_logger = "0.6.1"